server:
  port: 9004
spring:
  application:
    name: service-order
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bingo?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
#        server-addr: 1.116.179.183:8848
        server-addr: 127.0.0.1:8848
  redis:
#    host: 1.116.179.183
    host: 172.16.1.10
    timeout: 1800000
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间 负数表示没有限制
        max-idle: 5
        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    call-setters-on-nulls: true



