server:
  port: 8888

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-management
          uri: lb://service-management
          predicates:
            - Path=/management/** # 路径匹配
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/fileoss/** # 路径匹配
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/order/** # 路径匹配
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/msm/** # 路径匹配

    nacos:
      discovery:
#        server-addr: 1.116.179.183:8848
        server-addr: 127.0.0.1:8848